schema_version: "2"
logical_identities: 00_logical_identities.yaml
nodes:
  - appeal.yaml
  - benefit.yaml
  - bridge.yaml
  - care.yaml
  - claim.yaml
  - edi.yaml
  - eligibility.yaml
  - member.yaml
  - organization.yaml
  - pharmacy.yaml
  - premium.yaml
  - provider.yaml
  - reference.yaml
  - remit.yaml
  - um.yaml
edges: 99_relationships.yaml
