schema_version: "2"
logical_identities: 00_logical_identities.yaml
nodes:
  - billing.yaml
  - bridge.yaml
  - care.yaml
  - charging.yaml
  - finance.yaml
  - mediation.yaml
  - network.yaml
  - organization.yaml
  - party.yaml
  - product.yaml
  - reference.yaml
  - roaming.yaml
  - usage.yaml
edges: 99_relationships.yaml
